### ISSUE TITLE
vs DotKill

### ISSUE THREAD

**Issue by realfinder** [Asd-g/AviSynth-bifrost#1]
Hi, since you port/update Rainbow and Dot Crawl plugins, is it possible to port this new one? https://github.com/myrsloik/DotKill more info https://web.archive.org/web/20160927234818/http://forum.doom9.org/showthread.php?t=173029

thanks

**Comment by SangenBR** [comment]
is better than the checkmate?

**Comment by realfinder** [comment]
> 
> 
> is better than the checkmate?

it's seems better than checkmate

**Comment by nobananasforyou** [comment]
Checkmate causes artefacts in scenes with motion and/or at scene change.

**Comment by SangenBR** [comment]
> Checkmate causes artefacts in scenes with motion and/or at scene change.

really, I already gave up many things that I wanted to encode because of these artifacts

**Comment by kedaitinh12** [comment]
Can you port BM3D (the best denoiser)??
https://github.com/HomeOfVapourSynthEvolution/VapourSynth-BM3D

And this script use very good with BM3D:
https://github.com/IFeelBloated/Oyster

Thanks

**Comment by kedaitinh12** [comment]
Here:
https://github.com/Asd-g/AviSynth-DotKill

**Comment by kedaitinh12** [comment]
BM3D now have CUDA ver and new fix
https://github.com/WolframRhodium/VapourSynth-BM3DCUDA

**Comment by kedaitinh12** [comment]
BM3D now on avs ver
https://github.com/WolframRhodium/VapourSynth-BM3DCUDA/issues/7#issuecomment-886173346

**Comment by Asd-g** [comment]
Thanks for the info.

**Comment by kedaitinh12** [comment]
fmtconv now available in avs,
https://github.com/EleonoreMizo/fmtconv/releases
Now this script have all requirements available in avs
https://github.com/IFeelBloated/Oyster

**Comment by Asd-g** [comment]
Did you use that script for anything other than experimenting?

**Comment by kedaitinh12** [comment]
Yes, i was used in vs and that script perfome good in fine details

**Comment by kedaitinh12** [comment]
Dogway was ported to avs+, sr for disturb
https://github.com/Dogway/Avisynth-Scripts/blob/401b6900513a9fb5396f272c0885812139901858/EX%20mods/DeblockPack.avsi#L149

**Comment by Asd-g** [comment]
Thanks for the info.
